modLoader="javafml"
loaderVersion="[4,)"
license="GPL-3.0-only"
issueTrackerURL="https://github.com/EyeCrasher07/LazoDiscs/issues"

[[mods]]
modId="lazodiscs"
version="1.0.1+mc1.21.10"
displayName="LazoDiscs"
displayTest="IGNORE_ALL_VERSION"
logoFile="lazodiscs_icon.png"
authors="EyeCrasher"
description='''
Custom URL music discs for NeoForge using Plasmo Voice positional audio.
Server-side mod for dedicated servers, with integrated singleplayer server support. Port for Minecraft 1.21.10.
'''

[[mixins]]
config="lazodiscs.mixins.json"

[[dependencies.lazodiscs]]
modId="neoforge"
type="required"
versionRange="[21.10.0,)"
ordering="NONE"
side="BOTH"

[[dependencies.lazodiscs]]
modId="minecraft"
type="required"
versionRange="[1.21.10,1.21.11)"
ordering="NONE"
side="BOTH"

[[dependencies.lazodiscs]]
modId="plasmovoice"
type="required"
versionRange="[2.1.0,)"
ordering="AFTER"
side="SERVER"
