modLoader="javafml"
loaderVersion="[37,)"
license="GPL-3.0-only"
issueTrackerURL="https://github.com/EyeCrasher07/LazoDiscs/issues"

[[mods]]
modId="lazodiscs"
version="${version}"
displayName="LazoDiscs"
displayTest="IGNORE_ALL_VERSION"
logoFile="lazodiscs_icon.png"
authors="EyeCrasher"
description='''
Custom music discs with Plasmo Voice positional audio.
Burn YouTube, YouTube Music, SoundCloud, Spotify track links, and direct playable audio URLs onto vanilla music discs.
Supports dedicated servers and integrated singleplayer servers.
'''

[[dependencies.lazodiscs]]
modId="forge"
mandatory=true
versionRange="[37.1.1,38)"
ordering="NONE"
side="BOTH"

[[dependencies.lazodiscs]]
modId="minecraft"
mandatory=true
versionRange="[1.17.1,1.17.2)"
ordering="NONE"
side="BOTH"

[[dependencies.lazodiscs]]
modId="plasmovoice"
mandatory=true
versionRange="[2.1.8,)"
ordering="AFTER"
side="BOTH"

[[dependencies.lazodiscs]]
modId="sophisticatedcore"
mandatory=false
versionRange="[1.5.0,)"
ordering="AFTER"
side="BOTH"

[[dependencies.lazodiscs]]
modId="sophisticatedbackpacks"
mandatory=false
versionRange="[3.20.0,)"
ordering="AFTER"
side="BOTH"

[[dependencies.lazodiscs]]
modId="sable"
mandatory=false
versionRange="[2.0.0,)"
ordering="AFTER"
side="BOTH"
